[LogConfiguration]
; This file controls how the log entires look. Editing these can cause logs to become nonfunctional, so be careful.
; Each logtype will mention what data is available and what their formatter is.

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <id> = Client ID
; <ipid> = Client IPID
; <area> = Area Name
; <message> = Message
ic="[<time>][<area>][IC][<id>][<char>(<ooc>)][<ipid>]: <message>"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <id> = Client ID
; <ipid> = Client IPID
; <area> = Area Name
; <message> = Message
ooc="[<time>][<area>][OOC][<id>][<char>(<ooc>)][<ipid>]: <message>"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <id> = Client ID
; <ipid> = Client IPID
; <area> = Area Name
; <track> = track Name
music="[<time>][<area>][MUSIC][<id>][<char>(<ooc>)][<ipid>]: <track>"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <ipid> = Client IPID
; <passed> = Success/Fail
login="[<time>][LOGIN][<char>(<ooc>)][<ipid>]: <passed>"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <ipid> = Client IPID
; <area> = Area Name
cmdlogin="[<time>][<area>][LOGIN][<ipid>][<char>(<ooc>)]"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <ipid> = Client IPID
; <area> = Area Name
cmdrootpass="[<time>][<area>][ROOTPASS][<ipid>][<char>(<ooc>)]"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <ipid> = Client IPID
; <area> = Area Name
; <user> = Username
cmdadduser="[<time>][<area>][USERADD][<ipid>][<char>(<ooc>)] <user>"

; <time> = Event Time
; <char> = Character Name
; <ooc> = Out-Of-Courtroom Name
; <ipid> = Client IPID
; <area> = Area Name
; <user> = Username
; <cmd_name> = Command Name
; <cmd_arg> = Command Arguments
cmd="[<time>][<area>][CMD][<ipid>][<char>(<ooc>)]: /<cmd_name> <cmd_arg>"

; <time> = Event Time
; <m_name> = Moderator Name
; <ipid> = Kicked Client IPID
kick="[<time>][<m_name>][KICK][<ipid>]"

; <time> = Event Time
; <m_name> = Moderator Name
; <ipid> = Banned Client IPID
; <duration> = Ban Duration
ban="[<time>][<m_name>][BAN][<ipid>][<duration>]"

; <time> = Event Time
; <char> = Character Name
; <area> = Area Name
; <ooc> = Out-Of-Courtroom Name
; <id> = Client ID
; <ipid> = Client IPID
modcall="[<time>][<area>][MODCALL][<id>][<ipid>][<char>(<ooc>)]"

; <time> = Event Time
; <ip> = IP Address
; <ipid> = Client IPID
; <hwid> = Client HWID
connect="[<time>][CONNECT][<ip>][<ipid>][<hwid>]"